name: til CD

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        name: Cache environment
        with:
          path: ~/.cache/pip
          key: environment-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            environment-${{ runner.os }}-
      - name: Configure environment
        run: |
          python -m pip install -r requirements.txt
      - name: Update README
        run: |-
          python populate_readme.py
      - name: Commit and push changes
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated content" || exit 0
          git push